const CAFES = [
  {
    id: '1',
    name: 'Concordia 1',
    location: 'Near NBS Ground',
    description: 'Quick bites, great chai, and a chill vibe between classes. The go-to spot when you have 10 minutes between lectures.',
    baseRating: 4.2,
    baseReviews: 124,
    emoji: '☕',
    menu: [
      { cat: 'BBQ', items: [
        { id: 'c1-bbq1', name: 'Chicken Achari Boti',        price: 350 },
        { id: 'c1-bbq2', name: 'Chicken Cheese Kebab 4Pc',   price: 450 },
        { id: 'c1-bbq3', name: 'Chicken Golden Boti 6Pc',    price: 380 },
        { id: 'c1-bbq4', name: 'Chicken Kebab 4Pc',          price: 360 },
        { id: 'c1-bbq5', name: 'Chicken Malai Boti 6Pc',     price: 380 },
        { id: 'c1-bbq6', name: 'Chicken Reshmi Kebab 4Pc',   price: 450 },
        { id: 'c1-bbq7', name: 'Chicken Tikka Boti',         price: 350 },
        { id: 'c1-bbq8', name: 'Chicken Tikka Piece',        price: 350 },
      ]},
      { cat: 'Bread', items: [
        { id: 'c1-br1', name: 'Naan Sada',    price: 30 },
        { id: 'c1-br2', name: 'Roghni Naan',  price: 50 },
        { id: 'c1-br3', name: 'Roti',         price: 25 },
      ]},
      { cat: 'Burgers', items: [
        { id: 'c1-burg1',  name: 'Anda Shami Burger',           price: 180 },
        { id: 'c1-burg2',  name: 'Chapli Kebab Burger',         price: 300 },
        { id: 'c1-burg3',  name: 'Chicken Cheese Burger',       price: 340 },
        { id: 'c1-burg4',  name: 'Chicken Cheese Shami Burger', price: 200 },
        { id: 'c1-burg5',  name: 'Chicken Crispy Burger',       price: 350 },
        { id: 'c1-burg6',  name: 'Chicken Egg Burger',          price: 350 },
        { id: 'c1-burg7',  name: 'Chicken Fillet Burger',       price: 280 },
        { id: 'c1-burg8',  name: 'Chicken Fillet Cheese Burger',price: 340 },
        { id: 'c1-burg9',  name: 'Chicken Shami Burger',        price: 150 },
        { id: 'c1-burg10', name: 'Shami Burger',                price: 150 },
        { id: 'c1-burg11', name: 'Zinger Burger',               price: 320 },
      ]},
      { cat: 'Chinese', items: [
        { id: 'c1-ch1', name: 'Chicken Chowmein', price: 250 },
      ]},
      { cat: 'Coffee', items: [
        { id: 'c1-cof1', name: 'Cold Coffee', price: 280 },
      ]},
      { cat: 'Desserts', items: [
        { id: 'c1-des1',  name: 'Banana Bread',            price: 160 },
        { id: 'c1-des2',  name: 'Brownie',                 price: 200 },
        { id: 'c1-des3',  name: 'Choco Caramel Brownie',   price: 220 },
        { id: 'c1-des4',  name: 'Chocolate Mousse',        price: 220 },
        { id: 'c1-des5',  name: 'Chocolate Pop',           price: 90  },
        { id: 'c1-des6',  name: 'Cream Roll',              price: 160 },
        { id: 'c1-des7',  name: 'Donut',                   price: 150 },
        { id: 'c1-des8',  name: 'Double Chocolate Pastry', price: 220 },
        { id: 'c1-des9',  name: 'Filled Donut',            price: 120 },
        { id: 'c1-des10', name: 'Fudge Brownie',           price: 230 },
        { id: 'c1-des11', name: 'KitKat Cake Slice',       price: 250 },
        { id: 'c1-des12', name: 'KitKat Pastry',           price: 220 },
        { id: 'c1-des13', name: 'Pastry',                  price: 160 },
        { id: 'c1-des14', name: 'Pineapple Pastry',        price: 220 },
        { id: 'c1-des15', name: 'Red Velvet Cake Slice',   price: 250 },
      ]},
      { cat: 'Drinks', items: [
        { id: 'c1-drk1', name: 'Bottle 375ml',    price: 60  },
        { id: 'c1-drk2', name: 'Ice Tea',         price: 150 },
        { id: 'c1-drk3', name: 'Lemon Ice Tea',   price: 150 },
        { id: 'c1-drk4', name: 'Mango Ice Tea',   price: 150 },
        { id: 'c1-drk5', name: 'Mint Margarita',  price: 150 },
        { id: 'c1-drk6', name: 'Peach Ice Tea',   price: 150 },
      ]},
      { cat: 'Extras', items: [
        { id: 'c1-ext1', name: 'Aloo Samosa',          price: 50  },
        { id: 'c1-ext2', name: 'Chicken Samosa',        price: 70  },
        { id: 'c1-ext3', name: 'Double Samosa Chaat',   price: 180 },
        { id: 'c1-ext4', name: 'Single Samosa Chaat',   price: 110 },
        { id: 'c1-ext5', name: 'Vegetable Samosa',      price: 50  },
        { id: 'c1-ext6', name: 'Water Bottle 1.5 Liter',price: 100 },
      ]},
      { cat: 'Fries', items: [
        { id: 'c1-fr1',  name: 'Chicken Fries 12Pcs',             price: 450 },
        { id: 'c1-fr2',  name: 'Chicken Fries 6Pcs',              price: 250 },
        { id: 'c1-fr3',  name: 'Chicken Nuggets/Fries 12Pcs',     price: 450 },
        { id: 'c1-fr4',  name: 'Chicken Nuggets/Fries 6Pcs',      price: 250 },
        { id: 'c1-fr5',  name: 'Chicken Nuggets/Fries BBQ 12Pcs', price: 500 },
        { id: 'c1-fr6',  name: 'Chicken Nuggets/Fries BBQ 6Pcs',  price: 300 },
        { id: 'c1-fr7',  name: 'Fries Regular Large',             price: 240 },
        { id: 'c1-fr8',  name: 'Fries Regular Small',             price: 180 },
        { id: 'c1-fr9',  name: 'Loaded Fries Large',              price: 500 },
        { id: 'c1-fr10', name: 'Loaded Fries Regular',            price: 350 },
        { id: 'c1-fr11', name: 'Oppa Fries',                      price: 240 },
      ]},
      { cat: 'Hot Drinks', items: [
        { id: 'c1-hd1', name: 'Cardamom Tea',     price: 110 },
        { id: 'c1-hd2', name: 'Coffee',           price: 150 },
        { id: 'c1-hd3', name: 'Double Tea Pack',  price: 70  },
        { id: 'c1-hd4', name: 'Green Tea',        price: 40  },
        { id: 'c1-hd5', name: 'Hot Chocolate',    price: 150 },
        { id: 'c1-hd6', name: 'Nes-Tea',          price: 110 },
        { id: 'c1-hd7', name: 'Single Tea Pack',  price: 60  },
        { id: 'c1-hd8', name: 'Tea Parcel',       price: 200 },
        { id: 'c1-hd9', name: 'Tea Single Tea Bag',price: 60 },
      ]},
      { cat: 'Ice Cream', items: [
        { id: 'c1-ic1',  name: 'Ice Cream 1 Scoop',              price: 90  },
        { id: 'c1-ic2',  name: 'Ice Cream 2 Scoops',             price: 160 },
        { id: 'c1-ic3',  name: 'Ice Cream 3 Scoops',             price: 230 },
        { id: 'c1-ic4',  name: 'Chocolate Single',               price: 90  },
        { id: 'c1-ic5',  name: 'Chocolate Double',               price: 160 },
        { id: 'c1-ic6',  name: 'Chocolate Triple',               price: 230 },
        { id: 'c1-ic7',  name: 'Coconut Single',                 price: 90  },
        { id: 'c1-ic8',  name: 'Coconut Double',                 price: 160 },
        { id: 'c1-ic9',  name: 'Coconut Triple',                 price: 230 },
        { id: 'c1-ic10', name: 'Coffee Single',                  price: 90  },
        { id: 'c1-ic11', name: 'Coffee Double',                  price: 160 },
        { id: 'c1-ic12', name: 'Coffee Triple',                  price: 230 },
        { id: 'c1-ic13', name: 'Gulfa Single',                   price: 90  },
        { id: 'c1-ic14', name: 'Gulfa Double',                   price: 160 },
        { id: 'c1-ic15', name: 'Gulfa Triple',                   price: 230 },
        { id: 'c1-ic16', name: 'Mango Single',                   price: 90  },
        { id: 'c1-ic17', name: 'Mango Double',                   price: 160 },
        { id: 'c1-ic18', name: 'Mango Triple',                   price: 230 },
        { id: 'c1-ic19', name: 'Pistachio Single',               price: 90  },
        { id: 'c1-ic20', name: 'Pistachio Double',               price: 160 },
        { id: 'c1-ic21', name: 'Pistachio Triple',               price: 230 },
        { id: 'c1-ic22', name: 'Roasted Almond Single',          price: 90  },
        { id: 'c1-ic23', name: 'Roasted Almond Double',          price: 160 },
        { id: 'c1-ic24', name: 'Roasted Almond Triple',          price: 230 },
        { id: 'c1-ic25', name: 'Strawberry Single',              price: 90  },
        { id: 'c1-ic26', name: 'Strawberry Double',              price: 160 },
        { id: 'c1-ic27', name: 'Strawberry Triple',              price: 230 },
        { id: 'c1-ic28', name: 'Vanilla Single',                 price: 90  },
        { id: 'c1-ic29', name: 'Vanilla Double',                 price: 160 },
        { id: 'c1-ic30', name: 'Vanilla Triple',                 price: 230 },
      ]},
      { cat: 'Juices', items: [
        { id: 'c1-ju1', name: 'Apple Juice',              price: 280 },
        { id: 'c1-ju2', name: 'Carrot Juice',             price: 150 },
        { id: 'c1-ju3', name: 'Falsa Juice',              price: 200 },
        { id: 'c1-ju4', name: 'Grapefruit Juice',         price: 180 },
        { id: 'c1-ju5', name: 'Orange Juice',             price: 200 },
        { id: 'c1-ju6', name: 'Pineapple Juice',          price: 270 },
        { id: 'c1-ju7', name: 'Pomegranate Juice',        price: 400 },
        { id: 'c1-ju8', name: 'Strawberry Juice',         price: 200 },
        { id: 'c1-ju9', name: 'Sweet Lime Mosambi Juice', price: 200 },
      ]},
      { cat: 'Pasta', items: [
        { id: 'c1-pa1', name: 'Chicken Macaroni', price: 250 },
      ]},
      { cat: 'Pizza', items: [
        { id: 'c1-pz1',  name: 'Cheese Pizza Large',       price: 1600 },
        { id: 'c1-pz2',  name: 'Cheese Pizza Medium',      price: 1250 },
        { id: 'c1-pz3',  name: 'Cheese Pizza Small',       price: 850  },
        { id: 'c1-pz4',  name: 'Cheese Pizza XL',          price: 1900 },
        { id: 'c1-pz5',  name: 'Donut Pizza Large',        price: 1250 },
        { id: 'c1-pz6',  name: 'Donut Pizza Medium',       price: 450  },
        { id: 'c1-pz7',  name: 'Donut Pizza Small',        price: 350  },
        { id: 'c1-pz8',  name: 'Donut Pizza XL',           price: 1600 },
        { id: 'c1-pz9',  name: 'Mini Pizza',               price: 180  },
        { id: 'c1-pz10', name: 'Pizza Bread',              price: 150  },
        { id: 'c1-pz11', name: 'Pizza C1 Special XL',      price: 1400 },
        { id: 'c1-pz12', name: 'Pizza Large',              price: 1200 },
        { id: 'c1-pz13', name: 'Pizza Medium',             price: 830  },
        { id: 'c1-pz14', name: 'Pizza Roll',               price: 220  },
        { id: 'c1-pz15', name: 'Pizza Small',              price: 430  },
        { id: 'c1-pz16', name: 'Pizza XL',                 price: 1400 },
        { id: 'c1-pz17', name: 'Small Pizza',              price: 220  },
        { id: 'c1-pz18', name: 'Thin Crispy Crust XL',     price: 1800 },
      ]},
      { cat: 'Rice', items: [
        { id: 'c1-ri1',  name: 'Chicken Biryani',      price: 280 },
        { id: 'c1-ri2',  name: 'Chicken Fried Rice',   price: 300 },
        { id: 'c1-ri3',  name: 'Chicken Kabuli Pulao', price: 320 },
        { id: 'c1-ri4',  name: 'Chicken Pulao',        price: 280 },
        { id: 'c1-ri5',  name: 'Egg Fried Rice',       price: 240 },
        { id: 'c1-ri6',  name: 'Manchurian Rice',      price: 350 },
        { id: 'c1-ri7',  name: 'Shashlik Rice',        price: 280 },
        { id: 'c1-ri8',  name: 'Simple Biryani',       price: 200 },
        { id: 'c1-ri9',  name: 'Simple Fried Rice',    price: 180 },
        { id: 'c1-ri10', name: 'Simple Pulao',         price: 200 },
      ]},
      { cat: 'Roll', items: [
        { id: 'c1-ro1', name: 'Zinger Roll', price: 320 },
      ]},
      { cat: 'Roll Paratha', items: [
        { id: 'c1-rp1',  name: 'Boom Boom Roll Paratha',                  price: 500 },
        { id: 'c1-rp2',  name: 'Chicken Bihari Roll Paratha',             price: 250 },
        { id: 'c1-rp3',  name: 'Chicken Chapati Tikka Boti Roll Paratha', price: 250 },
        { id: 'c1-rp4',  name: 'Chicken Cheese Kebab Roll Paratha',       price: 250 },
        { id: 'c1-rp5',  name: 'Chicken Jumbo Cheese Roll Paratha',       price: 450 },
        { id: 'c1-rp6',  name: 'Chicken Jumbo Roll Paratha',              price: 400 },
        { id: 'c1-rp7',  name: 'Chicken Kebab Roll Paratha',              price: 200 },
        { id: 'c1-rp8',  name: 'Chicken Malai Roll Paratha',              price: 350 },
        { id: 'c1-rp9',  name: 'Chicken Mayo Garlic Roll Paratha',        price: 280 },
        { id: 'c1-rp10', name: 'Chicken Plain Roll Paratha',              price: 250 },
        { id: 'c1-rp11', name: 'Chicken Special Roll Paratha',            price: 300 },
        { id: 'c1-rp12', name: 'Chicken Spicy Roll Paratha',              price: 250 },
        { id: 'c1-rp13', name: 'Chicken Zinger Roll Paratha',             price: 300 },
        { id: 'c1-rp14', name: 'Tortilla Wrap',                          price: 260 },
        { id: 'c1-rp15', name: 'Vegetable Roll Paratha',                 price: 200 },
      ]},
      { cat: 'Rolls', items: [
        { id: 'c1-rls1', name: 'Chicken Paratha Roll', price: 250 },
        { id: 'c1-rls2', name: 'Chicken Roll',         price: 70  },
        { id: 'c1-rls3', name: 'Chicken Roll Paratha', price: 350 },
        { id: 'c1-rls4', name: 'Sausage Roll',         price: 150 },
        { id: 'c1-rls5', name: 'Vegetable Roll',       price: 50  },
      ]},
      { cat: 'Salad', items: [
        { id: 'c1-sal1', name: 'Salad Bowl Chicken Tikka/Fajita', price: 300 },
      ]},
      { cat: 'Salan', items: [
        { id: 'c1-sln1', name: 'Chicken Crispy Piece', price: 130  },
        { id: 'c1-sln2', name: 'Chicken Haleem',       price: 200  },
        { id: 'c1-sln3', name: 'Chicken Jalfrezi',     price: 300  },
        { id: 'c1-sln4', name: 'Chicken Karahi Full',  price: 1600 },
        { id: 'c1-sln5', name: 'Chicken Karahi Half',  price: 900  },
        { id: 'c1-sln6', name: 'Chicken Kofta',        price: 280  },
        { id: 'c1-sln7', name: 'Chicken Korma',        price: 280  },
        { id: 'c1-sln8', name: 'Daal Mash',            price: 180  },
        { id: 'c1-sln9', name: 'Daal/Chana/Sabzi',     price: 150  },
      ]},
      { cat: 'Sandwiches', items: [
        { id: 'c1-sw1', name: 'Chicken Cheese Sandwich',  price: 150 },
        { id: 'c1-sw2', name: 'Chicken Club Sandwich',    price: 350 },
        { id: 'c1-sw3', name: 'Chicken Egg Sandwich',     price: 210 },
        { id: 'c1-sw4', name: 'Chicken Panini Sandwich',  price: 300 },
        { id: 'c1-sw5', name: 'Chicken Sandwich Double',  price: 210 },
        { id: 'c1-sw6', name: 'Chicken Tikka Sandwich',   price: 220 },
        { id: 'c1-sw7', name: 'Club Sandwich',            price: 210 },
      ]},
      { cat: 'Shakes', items: [
        { id: 'c1-sh1',  name: 'Apple Banana Shake',  price: 200 },
        { id: 'c1-sh2',  name: 'Apple Shake',         price: 200 },
        { id: 'c1-sh3',  name: 'Banana Oreo Shake',   price: 210 },
        { id: 'c1-sh4',  name: 'Banana Shake',        price: 200 },
        { id: 'c1-sh5',  name: 'Brownie Shake',       price: 250 },
        { id: 'c1-sh6',  name: 'Chocolate Shake',     price: 210 },
        { id: 'c1-sh7',  name: 'Cold Coffee Shake',   price: 210 },
        { id: 'c1-sh8',  name: 'Dates Shake',         price: 220 },
        { id: 'c1-sh9',  name: 'Ice Cream Shake',     price: 300 },
        { id: 'c1-sh10', name: 'Milk Shake',          price: 280 },
        { id: 'c1-sh11', name: 'Milo Shake',          price: 210 },
        { id: 'c1-sh12', name: 'Oreo Shake',          price: 200 },
        { id: 'c1-sh13', name: 'Strawberry Shake',    price: 200 },
      ]},
      { cat: 'Shawarma', items: [
        { id: 'c1-sha1', name: 'Chicken Shawarma', price: 240 },
      ]},
      { cat: 'Sides', items: [
        { id: 'c1-sid1', name: 'Aloo Shami',            price: 50  },
        { id: 'c1-sid2', name: 'Chana Chaat/Papri Chaat',price: 160 },
        { id: 'c1-sid3', name: 'Dahi Baray',            price: 160 },
        { id: 'c1-sid4', name: 'Fruit Chaat',           price: 220 },
      ]},
      { cat: 'Slush', items: [
        { id: 'c1-sl1', name: 'Slush',              price: 220 },
        { id: 'c1-sl2', name: 'Slush Blackcurrant', price: 220 },
        { id: 'c1-sl3', name: 'Slush Blueberry',    price: 220 },
        { id: 'c1-sl4', name: 'Slush Strawberry',   price: 220 },
      ]},
      { cat: 'Snacks', items: [
        { id: 'c1-sn1', name: 'Chicken Butter Patties',       price: 120 },
        { id: 'c1-sn2', name: 'Chicken Cheese Croquettes 12Pcs',price: 350},
        { id: 'c1-sn3', name: 'Chicken Cheese Croquettes 6Pcs', price: 200},
        { id: 'c1-sn4', name: 'Chicken Croquettes 12Pcs',     price: 400 },
        { id: 'c1-sn5', name: 'Chicken Croquettes 6Pcs',      price: 220 },
        { id: 'c1-sn6', name: 'Chicken Nuggets 12Pcs',        price: 450 },
        { id: 'c1-sn7', name: 'Chicken Nuggets 6Pcs',         price: 250 },
        { id: 'c1-sn8', name: 'Pakora Plate',                 price: 200 },
      ]},
      { cat: 'Soda', items: [
        { id: 'c1-so1', name: 'Bottle 1 Liter Pepsi',       price: 200 },
        { id: 'c1-so2', name: 'Bottle 1.5L Pepsi',          price: 10  },
        { id: 'c1-so3', name: 'Bottle Gourmet 1.5 Liter',   price: 180 },
        { id: 'c1-so4', name: 'Bottle Gourmet Half Liter',  price: 100 },
        { id: 'c1-so5', name: 'Water Bottle Half Liter',    price: 50  },
      ]},
      { cat: 'Soup', items: [
        { id: 'c1-soup1', name: 'Chicken Corn Soup Large', price: 170 },
        { id: 'c1-soup2', name: 'Chicken Corn Soup Small', price: 120 },
      ]},
      { cat: 'Tea', items: [
        { id: 'c1-tea1', name: 'Pink Tea', price: 150 },
      ]},
      { cat: 'Wings', items: [
        { id: 'c1-wng1', name: 'Wings 6 Piece', price: 500 },
      ]},
    ]
  },
  {
    id: '2',
    name: 'Concordia 2',
    location: 'Near SEECS',
    description: 'Fuel for late-night lab sessions. The favorite of CS and EE students — always packed after 8 pm, somehow still manages fast service.',
    baseRating: 4.5,
    baseReviews: 207,
    emoji: '⚡',
    menu: [
      { cat: 'BBQ', items: [
        { id: 'c2-bbq1', name: 'Chicken Achari Boti Plate',      price: 380 },
        { id: 'c2-bbq2', name: 'Chicken Bala Leg Piece',         price: 180 },
        { id: 'c2-bbq3', name: 'Chicken Malai Boti 5 Pieces',    price: 380 },
        { id: 'c2-bbq4', name: 'Chicken Malai Boti 8 Pieces',    price: 500 },
        { id: 'c2-bbq5', name: 'Chicken Reshmi Kebab',           price: 400 },
        { id: 'c2-bbq6', name: 'Chicken Seekh Kebab 4 Pieces',   price: 350 },
        { id: 'c2-bbq7', name: 'Chicken Tikka Boti Plate',       price: 350 },
        { id: 'c2-bbq8', name: 'Chicken Tikka Masala Boti Plate',price: 450 },
        { id: 'c2-bbq9', name: 'Chicken Tikka Piece',            price: 350 },
      ]},
      { cat: 'Breakfast', items: [
        { id: 'c2-bk1',  name: 'Aloo Paratha',              price: 140 },
        { id: 'c2-bk2',  name: 'Aloo Paratha Cheese',       price: 210 },
        { id: 'c2-bk3',  name: 'Bread Slice',               price: 30  },
        { id: 'c2-bk4',  name: 'Chicken Cheese Roll Paratha',price: 270 },
        { id: 'c2-bk5',  name: 'Chicken Paratha',           price: 200 },
        { id: 'c2-bk6',  name: 'Chicken Roll Paratha',      price: 250 },
        { id: 'c2-bk7',  name: 'Fried Omelette',            price: 60  },
        { id: 'c2-bk8',  name: 'Lachha Paratha',            price: 100 },
        { id: 'c2-bk9',  name: 'Omelette Cheese',           price: 120 },
        { id: 'c2-bk10', name: 'Paratha',                   price: 60  },
        { id: 'c2-bk11', name: 'Paratha Cheese',            price: 120 },
      ]},
      { cat: 'Burgers', items: [
        { id: 'c2-burg1',  name: 'Afghani Burger Double',    price: 300 },
        { id: 'c2-burg2',  name: 'Afghani Burger Plain',     price: 200 },
        { id: 'c2-burg3',  name: 'Afghani Burger Single',    price: 250 },
        { id: 'c2-burg4',  name: 'Chapli Kebab Burger',      price: 300 },
        { id: 'c2-burg5',  name: 'Chicken Cheese Burger',    price: 340 },
        { id: 'c2-burg6',  name: 'Chicken Zinger Burger',    price: 320 },
        { id: 'c2-burg7',  name: 'Egg Shami Burger',         price: 180 },
        { id: 'c2-burg8',  name: 'Grilled Chicken Burger',   price: 420 },
        { id: 'c2-burg9',  name: 'Hot Dog Cheese Burger',    price: 280 },
        { id: 'c2-burg10', name: 'Shami Burger',             price: 150 },
        { id: 'c2-burg11', name: 'Tikka Burger',             price: 350 },
      ]},
      { cat: 'Desserts', items: [
        { id: 'c2-des1',  name: 'Banana Bread',              price: 180 },
        { id: 'c2-des2',  name: 'Brownie',                   price: 220 },
        { id: 'c2-des3',  name: 'Chocolate Brownie',         price: 250 },
        { id: 'c2-des4',  name: 'Chocolate Chip Cake Slice', price: 280 },
        { id: 'c2-des5',  name: 'Chocolate Eclair',          price: 170 },
        { id: 'c2-des6',  name: 'Chocolate Mousse Large',    price: 220 },
        { id: 'c2-des7',  name: 'Cookies',                   price: 180 },
        { id: 'c2-des8',  name: 'Cream Roll',                price: 160 },
        { id: 'c2-des9',  name: 'Donuts',                    price: 150 },
        { id: 'c2-des10', name: 'Filled Donut',              price: 240 },
        { id: 'c2-des11', name: 'Icing Cupcake',             price: 170 },
        { id: 'c2-des12', name: 'Mini Donut',                price: 130 },
        { id: 'c2-des13', name: 'Pastry',                    price: 230 },
      ]},
      { cat: 'Drinks', items: [
        { id: 'c2-drk1', name: 'Coffee',             price: 150 },
        { id: 'c2-drk2', name: 'Green Tea',          price: 50  },
        { id: 'c2-drk3', name: 'Hot Chocolate',      price: 240 },
        { id: 'c2-drk4', name: 'Nes Ice Tea',        price: 150 },
        { id: 'c2-drk5', name: 'Nestea',             price: 110 },
        { id: 'c2-drk6', name: 'Tea Double Tea Bag', price: 70  },
        { id: 'c2-drk7', name: 'Tea Single Tea Bag', price: 60  },
      ]},
      { cat: 'Fries', items: [
        { id: 'c2-fr1', name: 'French Fries OPPA', price: 250 },
        { id: 'c2-fr2', name: 'Large Fries',       price: 240 },
        { id: 'c2-fr3', name: 'Loaded Fries',      price: 370 },
        { id: 'c2-fr4', name: 'Small Fries',       price: 130 },
      ]},
      { cat: 'Juices', items: [
        { id: 'c2-ju1', name: 'Apple Juice',        price: 280 },
        { id: 'c2-ju2', name: 'Carrot Juice',       price: 150 },
        { id: 'c2-ju3', name: 'Lemon Mint Juice',   price: 150 },
        { id: 'c2-ju4', name: 'Orange Juice',       price: 200 },
        { id: 'c2-ju5', name: 'Peach Juice',        price: 200 },
        { id: 'c2-ju6', name: 'Pineapple Juice',    price: 270 },
        { id: 'c2-ju7', name: 'Pomegranate Juice',  price: 450 },
      ]},
      { cat: 'Pasta', items: [
        { id: 'c2-pa1', name: 'C2 Special Pasta',     price: 430 },
        { id: 'c2-pa2', name: 'Creamy Chicken Pasta', price: 400 },
      ]},
      { cat: 'Pizza', items: [
        { id: 'c2-pz1',  name: 'C2 Special Pizza Large',   price: 1400 },
        { id: 'c2-pz2',  name: 'C2 Special Pizza Medium',  price: 1000 },
        { id: 'c2-pz3',  name: 'C2 Special Pizza Small',   price: 500  },
        { id: 'c2-pz4',  name: 'Chicken Tikka Pizza Large',price: 1200 },
        { id: 'c2-pz5',  name: 'Chicken Tikka Pizza Medium',price: 800 },
        { id: 'c2-pz6',  name: 'Chicken Tikka Pizza Small',price: 400  },
        { id: 'c2-pz7',  name: 'Mini Pizza',               price: 240  },
        { id: 'c2-pz8',  name: 'Tikka Pizza Large',        price: 1300 },
        { id: 'c2-pz9',  name: 'Tikka Pizza Medium',       price: 870  },
        { id: 'c2-pz10', name: 'Tikka Pizza Small',        price: 450  },
        { id: 'c2-pz11', name: 'Tikka Pizza XL',           price: 1500 },
      ]},
      { cat: 'Roll Paratha', items: [
        { id: 'c2-rp1', name: 'Chicken Jumbo Cheese Roll Paratha', price: 400 },
        { id: 'c2-rp2', name: 'Chicken Jumbo Roll Paratha',        price: 300 },
        { id: 'c2-rp3', name: 'Chicken Malai Boti Roll Paratha',   price: 350 },
        { id: 'c2-rp4', name: 'Chicken Mayo Roll Paratha',         price: 250 },
        { id: 'c2-rp5', name: 'Chicken Roll Paratha Spicy',        price: 260 },
        { id: 'c2-rp6', name: 'Chicken Seekh Kebab Roll Paratha',  price: 260 },
        { id: 'c2-rp7', name: 'Zinger Roll Paratha',               price: 320 },
        { id: 'c2-rp8', name: 'Zinger Roll Paratha Cheese',        price: 370 },
      ]},
      { cat: 'Sandwiches', items: [
        { id: 'c2-sw1', name: 'Chicken Cheese Croissant Sandwich', price: 250 },
        { id: 'c2-sw2', name: 'Chicken Mayo Sandwich',             price: 200 },
        { id: 'c2-sw3', name: 'Chicken Sandwich',                  price: 210 },
        { id: 'c2-sw4', name: 'Chicken Tikka Sandwich',            price: 230 },
        { id: 'c2-sw5', name: 'Club Sandwich',                     price: 350 },
        { id: 'c2-sw6', name: 'Fried Sandwich',                    price: 240 },
        { id: 'c2-sw7', name: 'Panini Sandwich',                   price: 320 },
        { id: 'c2-sw8', name: 'Tikka Sandwich 2 Pieces',           price: 150 },
        { id: 'c2-sw9', name: 'Tikka Sandwich 4 Pieces',           price: 300 },
      ]},
      { cat: 'Shakes', items: [
        { id: 'c2-sh1', name: 'Apple Banana Shake', price: 200 },
        { id: 'c2-sh2', name: 'Banana Oreo Shake',  price: 210 },
        { id: 'c2-sh3', name: 'Chocolate Shake',    price: 200 },
        { id: 'c2-sh4', name: 'Cold Coffee Shake',  price: 200 },
        { id: 'c2-sh5', name: 'Date Shake',         price: 220 },
        { id: 'c2-sh6', name: 'Mango Shake',        price: 200 },
        { id: 'c2-sh7', name: 'Milo Shake',         price: 200 },
        { id: 'c2-sh8', name: 'Oreo Shake',         price: 200 },
      ]},
      { cat: 'Shawarma', items: [
        { id: 'c2-sha1', name: 'Chicken Cheese Shawarma', price: 280 },
        { id: 'c2-sha2', name: 'Chicken Shawarma',        price: 240 },
      ]},
      { cat: 'Snacks', items: [
        { id: 'c2-sn1', name: 'Chicken Bread',         price: 190 },
        { id: 'c2-sn2', name: 'Chicken Cheese Patties',price: 170 },
        { id: 'c2-sn3', name: 'Chicken Patties',       price: 150 },
        { id: 'c2-sn4', name: 'Chicken Shashlik Stick',price: 200 },
        { id: 'c2-sn5', name: 'Pakora Half',           price: 150 },
        { id: 'c2-sn6', name: 'Pizza Roll',            price: 190 },
        { id: 'c2-sn7', name: 'Roll',                  price: 70  },
        { id: 'c2-sn8', name: 'Samosa',                price: 50  },
      ]},
      { cat: 'Wraps', items: [
        { id: 'c2-wr1', name: 'Chicken Wrap',  price: 250 },
        { id: 'c2-wr2', name: 'Tortilla Wrap', price: 350 },
      ]},
    ]
  },
  {
    id: '3',
    name: 'Concordia 3',
    location: 'In front of NUST Main Office',
    description: 'The most central cafe on campus. Always buzzing with students from every department. Great for a quick bite or a long hangout.',
    baseRating: 3.9,
    baseReviews: 89,
    emoji: '🏛️',
    menu: [
      { cat: 'BBQ', items: [
        { id: 'c3-bbq1', name: 'Chicken Boti Boneless 12pcs',       price: 750 },
        { id: 'c3-bbq2', name: 'Chicken Boti Boneless 6pcs',        price: 380 },
        { id: 'c3-bbq3', name: 'Chicken Malai Boti Boneless 12pcs', price: 900 },
        { id: 'c3-bbq4', name: 'Chicken Malai Boti Boneless 6pcs',  price: 460 },
        { id: 'c3-bbq5', name: 'Chicken Tikka Leg Piece',           price: 380 },
        { id: 'c3-bbq6', name: 'Seekh Kabab 3pcs',                  price: 400 },
        { id: 'c3-bbq7', name: 'Seekh Kabab 6pcs',                  price: 800 },
      ]},
      { cat: 'Bread', items: [
        { id: 'c3-br1',  name: 'Aloo Achari Cheese Paratha', price: 200 },
        { id: 'c3-br2',  name: 'Aloo Achari Paratha',        price: 190 },
        { id: 'c3-br3',  name: 'Aloo Chicken Cheese Paratha',price: 300 },
        { id: 'c3-br4',  name: 'Aloo Paratha',               price: 150 },
        { id: 'c3-br5',  name: 'Anda Paratha',               price: 150 },
        { id: 'c3-br6',  name: 'Chicken Cheese Paratha',     price: 290 },
        { id: 'c3-br7',  name: 'Chicken Paratha',            price: 240 },
        { id: 'c3-br8',  name: 'Malai Paratha',              price: 150 },
        { id: 'c3-br9',  name: 'Meetha Paratha',             price: 100 },
        { id: 'c3-br10', name: 'Omelet Paratha',             price: 160 },
        { id: 'c3-br11', name: 'Paratha',                    price: 70  },
        { id: 'c3-br12', name: 'Quetta Paratha',             price: 70  },
      ]},
      { cat: 'Burgers', items: [
        { id: 'c3-burg1', name: 'Crispy Burger',           price: 280 },
        { id: 'c3-burg2', name: 'Fillet Burger',           price: 400 },
        { id: 'c3-burg3', name: 'Grill Burger With Fries', price: 550 },
        { id: 'c3-burg4', name: 'Zinger Burger',           price: 380 },
        { id: 'c3-burg5', name: 'Zinger Burger with Cheese',price: 450},
        { id: 'c3-burg6', name: 'Zinger Burger With Fries',price: 470 },
      ]},
      { cat: 'Chinese', items: [
        { id: 'c3-ch1', name: 'Chicken Chow Mein',  price: 300 },
        { id: 'c3-ch2', name: 'Chicken Corn Soup',  price: 200 },
      ]},
      { cat: 'Dessert', items: [
        { id: 'c3-des1', name: 'Mixed Fruit Box', price: 250 },
      ]},
      { cat: 'Extra', items: [
        { id: 'c3-ext1', name: 'Extra Cheese', price: 150 },
      ]},
      { cat: 'Fries', items: [
        { id: 'c3-fr1', name: 'BBQ Fries',       price: 150 },
        { id: 'c3-fr2', name: 'Garlic Mayo Fries',price: 160 },
        { id: 'c3-fr3', name: 'Loaded Fries',    price: 350 },
        { id: 'c3-fr4', name: 'Masala Fries',    price: 130 },
      ]},
      { cat: 'Hot Drinks', items: [
        { id: 'c3-hd1',  name: 'Black Coffee',      price: 260 },
        { id: 'c3-hd2',  name: 'Cappuccino Large',  price: 280 },
        { id: 'c3-hd3',  name: 'Cappuccino Medium', price: 200 },
        { id: 'c3-hd4',  name: 'Cardamom Tea',      price: 120 },
        { id: 'c3-hd5',  name: 'Doodh Patti',       price: 80  },
        { id: 'c3-hd6',  name: 'Green Tea',         price: 60  },
        { id: 'c3-hd7',  name: 'Hot Chocolate',     price: 240 },
        { id: 'c3-hd8',  name: 'Latte Coffee',      price: 200 },
        { id: 'c3-hd9',  name: 'Pink Tea',          price: 150 },
        { id: 'c3-hd10', name: 'Shakar Tea',        price: 100 },
        { id: 'c3-hd11', name: 'Tea Bag Chai',      price: 80  },
      ]},
      { cat: 'Ice Cream', items: [
        { id: 'c3-ic1', name: 'Cone Ice Cream Large',  price: 200 },
        { id: 'c3-ic2', name: 'Cone Ice Cream Medium', price: 150 },
        { id: 'c3-ic3', name: 'Cone Ice Cream Small',  price: 80  },
      ]},
      { cat: 'Juices', items: [
        { id: 'c3-ju1',  name: 'ABC Juice',              price: 250 },
        { id: 'c3-ju2',  name: 'Apple Juice',            price: 280 },
        { id: 'c3-ju3',  name: 'Carrot Juice',           price: 150 },
        { id: 'c3-ju4',  name: 'Grapefruit Juice',       price: 200 },
        { id: 'c3-ju5',  name: 'Mosambi Juice',          price: 200 },
        { id: 'c3-ju6',  name: 'OBC Juice',              price: 250 },
        { id: 'c3-ju7',  name: 'Orange Juice',           price: 200 },
        { id: 'c3-ju8',  name: 'Peach Juice',            price: 200 },
        { id: 'c3-ju9',  name: 'Pomegranate Juice',      price: 350 },
        { id: 'c3-ju10', name: 'Slush',                  price: 200 },
        { id: 'c3-ju11', name: 'Sweet Lime Mitha Juice', price: 200 },
      ]},
      { cat: 'Pasta', items: [
        { id: 'c3-pa1', name: 'Alfredo Pasta',       price: 600 },
        { id: 'c3-pa2', name: 'BBQ Spaghetti Pasta', price: 600 },
        { id: 'c3-pa3', name: 'Crunchy Pasta',       price: 600 },
        { id: 'c3-pa4', name: 'Lasagna',             price: 600 },
        { id: 'c3-pa5', name: 'Mac n Cheese Pasta',  price: 600 },
        { id: 'c3-pa6', name: 'Penne Pasta',         price: 600 },
        { id: 'c3-pa7', name: 'Pollo Romano',        price: 600 },
      ]},
      { cat: 'Pizza', items: [
        { id: 'c3-pz1', name: 'Family Pizza', price: 1800 },
        { id: 'c3-pz2', name: 'Large Pizza',  price: 1400 },
        { id: 'c3-pz3', name: 'Medium Pizza', price: 1300 },
        { id: 'c3-pz4', name: 'Mini Pizza',   price: 500  },
        { id: 'c3-pz5', name: 'Small Pizza',  price: 800  },
      ]},
      { cat: 'Rice', items: [
        { id: 'c3-ri1', name: 'Chicken Biryani',   price: 280 },
        { id: 'c3-ri2', name: 'Chicken Fried Rice', price: 400 },
        { id: 'c3-ri3', name: 'Chicken Pulao',      price: 280 },
        { id: 'c3-ri4', name: 'Egg Fried Rice',     price: 240 },
      ]},
      { cat: 'Roll', items: [
        { id: 'c3-ro1', name: 'Special Wrap', price: 350 },
      ]},
      { cat: 'Roll Paratha', items: [
        { id: 'c3-rp1',  name: 'Chicken Cheese Seekh Kabab Roll Paratha Jumbo',  price: 360 },
        { id: 'c3-rp2',  name: 'Chicken Cheese Seekh Kabab Roll Paratha Normal', price: 300 },
        { id: 'c3-rp3',  name: 'Chicken Malai Boti Roll Paratha Jumbo',          price: 360 },
        { id: 'c3-rp4',  name: 'Chicken Malai Boti Roll Paratha Normal',         price: 300 },
        { id: 'c3-rp5',  name: 'Chicken Roll Paratha',                           price: 250 },
        { id: 'c3-rp6',  name: 'Chicken Seekh Kabab Roll Paratha Jumbo',         price: 320 },
        { id: 'c3-rp7',  name: 'Chicken Seekh Kabab Roll Paratha Normal',        price: 250 },
        { id: 'c3-rp8',  name: 'Chicken Tikka Boti Cheese Roll Paratha Jumbo',   price: 360 },
        { id: 'c3-rp9',  name: 'Chicken Tikka Boti Cheese Roll Paratha Normal',  price: 300 },
        { id: 'c3-rp10', name: 'Chicken Tikka Boti Roll Paratha Jumbo',          price: 320 },
        { id: 'c3-rp11', name: 'Chicken Tikka Boti Roll Paratha Normal',         price: 250 },
        { id: 'c3-rp12', name: 'Zinger Roll Paratha',                            price: 350 },
      ]},
      { cat: 'Salan', items: [
        { id: 'c3-sln1',  name: 'Chicken Haleem',                    price: 200  },
        { id: 'c3-sln2',  name: 'Chicken Qorma',                     price: 280  },
        { id: 'c3-sln3',  name: 'Chicken Seekh Kabab Karahi Full',   price: 1800 },
        { id: 'c3-sln4',  name: 'Chicken Seekh Kabab Karahi Half',   price: 1000 },
        { id: 'c3-sln5',  name: 'Chicken Tikka Boti Karahi Boneless Full', price: 2200 },
        { id: 'c3-sln6',  name: 'Chicken Tikka Boti Karahi Boneless Half', price: 1300 },
        { id: 'c3-sln7',  name: 'Chicken Tikka Boti Karahi Full',    price: 1800 },
        { id: 'c3-sln8',  name: 'Chicken Tikka Boti Karahi Half',    price: 1000 },
        { id: 'c3-sln9',  name: 'Chicken White Karahi Bone Full',    price: 2000 },
        { id: 'c3-sln10', name: 'Chicken White Karahi Bone Half',    price: 1200 },
        { id: 'c3-sln11', name: 'Chicken White Karahi Boneless Full',price: 2500 },
        { id: 'c3-sln12', name: 'Chicken White Karahi Boneless Half',price: 1400 },
        { id: 'c3-sln13', name: 'Chicken White Qorma',               price: 280  },
        { id: 'c3-sln14', name: 'Daal Vegetable',                    price: 150  },
      ]},
      { cat: 'Sandwiches', items: [
        { id: 'c3-sw1', name: 'Chicken Sandwich', price: 250 },
        { id: 'c3-sw2', name: 'Club Sandwich',    price: 400 },
        { id: 'c3-sw3', name: 'Panini Sandwich',  price: 400 },
      ]},
      { cat: 'Shakes', items: [
        { id: 'c3-sh1',  name: 'Apple Banana Shake',         price: 200 },
        { id: 'c3-sh2',  name: 'Apple Shake',                price: 200 },
        { id: 'c3-sh3',  name: 'Banana Dates Shake',         price: 220 },
        { id: 'c3-sh4',  name: 'Banana Shake',               price: 200 },
        { id: 'c3-sh5',  name: 'Chocolate Ice Cream Shake',  price: 270 },
        { id: 'c3-sh6',  name: 'Chocolate Shake',            price: 210 },
        { id: 'c3-sh7',  name: 'Cold Coffee',                price: 210 },
        { id: 'c3-sh8',  name: 'Cold Coffee with Ice Cream', price: 280 },
        { id: 'c3-sh9',  name: 'Dates Shake',                price: 230 },
        { id: 'c3-sh10', name: 'Mixed Fruit Shake',          price: 220 },
        { id: 'c3-sh11', name: 'Oreo Banana Shake',          price: 220 },
        { id: 'c3-sh12', name: 'Oreo Shake',                 price: 200 },
        { id: 'c3-sh13', name: 'Peach Shake',                price: 200 },
        { id: 'c3-sh14', name: 'Special Oreo Ice Cream Shake',price: 280},
        { id: 'c3-sh15', name: 'Vanilla Ice Cream Shake',   price: 270 },
      ]},
      { cat: 'Shawarma', items: [
        { id: 'c3-sha1', name: 'Authentic Shawarma', price: 280 },
      ]},
      { cat: 'Sides', items: [
        { id: 'c3-sid1', name: 'Cheese Omelet', price: 120 },
        { id: 'c3-sid2', name: 'Egg Fried',     price: 60  },
        { id: 'c3-sid3', name: 'Omelet',        price: 80  },
      ]},
      { cat: 'Soda', items: [
        { id: 'c3-so1', name: 'Lemon Soda',    price: 150 },
        { id: 'c3-so2', name: 'Mint Margarita',price: 200 },
      ]},
      { cat: 'Wings', items: [
        { id: 'c3-wng1', name: 'BBQ Wings',          price: 700 },
        { id: 'c3-wng2', name: 'Chicken Fried Wings', price: 580 },
        { id: 'c3-wng3', name: 'Honey Wings',         price: 700 },
        { id: 'c3-wng4', name: 'Peri Peri Wings',     price: 700 },
      ]},
    ]
  },
  {
    id: '4',
    name: 'Ratro Cafe',
    location: 'Near Liaquat Hostel',
    description: 'Hostel-side favourite for BBQ, jumbo rolls and pizza. Big portions, late hours, and the shakes menu everyone ends up ordering from.',
    baseRating: 4.3,
    baseReviews: 61,
    emoji: '🍕',
    menu: [
      { cat: 'BBQ', items: [
        { id: 'c4-bbq1', name: 'Malai Boti 8Pc',        price: 540 },
        { id: 'c4-bbq2', name: 'Rajasthani Tikka 1Pc',  price: 200 },
        { id: 'c4-bbq3', name: 'Rajasthani Tikka 3Pc',  price: 500 },
        { id: 'c4-bbq4', name: 'Reshmi Kabab 4Pc',      price: 480 },
        { id: 'c4-bbq5', name: 'Seekh Kabab 4Pc',       price: 390 },
        { id: 'c4-bbq6', name: 'Tikka Boti 5Pc',        price: 410 },
        { id: 'c4-bbq7', name: 'Tikka Pieces',          price: 370 },
      ]},
      { cat: 'Burgers', items: [
        { id: 'c4-burg1', name: 'Chicken Cheese Burger',    price: 360 },
        { id: 'c4-burg2', name: 'Chicken Tikka Burger',     price: 360 },
        { id: 'c4-burg3', name: 'Egg Shami Burger',         price: 190 },
        { id: 'c4-burg4', name: 'Hot Shot',                 price: 500 },
        { id: 'c4-burg5', name: 'Shami Burger',             price: 150 },
        { id: 'c4-burg6', name: 'Zinger Burger',            price: 340 },
        { id: 'c4-burg7', name: 'Zinger Burger with Cheese',price: 410 },
        { id: 'c4-burg8', name: 'Zinger Burger with Fries', price: 430 },
        { id: 'c4-burg9', name: 'Zinger Chapli Kabab Burger',price: 320 },
      ]},
      { cat: 'Chaat', items: [
        { id: 'c4-cha1', name: 'Lahori Fruit Chaat',      price: 220 },
        { id: 'c4-cha2', name: 'Samosa',                  price: 50  },
        { id: 'c4-cha3', name: 'Samosa Chaat (Double)',   price: 180 },
        { id: 'c4-cha4', name: 'Samosa Chaat (Single)',   price: 110 },
      ]},
      { cat: 'Fries', items: [
        { id: 'c4-fr1', name: 'Fries', price: 160 },
      ]},
      { cat: 'Hot Drinks', items: [
        { id: 'c4-hd1', name: 'Black Tea',            price: 60  },
        { id: 'c4-hd2', name: 'Coffee',               price: 160 },
        { id: 'c4-hd3', name: 'Doodh Pati',           price: 90  },
        { id: 'c4-hd4', name: 'Green Tea',            price: 50  },
        { id: 'c4-hd5', name: 'Tea (Double Tea Bag)', price: 70  },
        { id: 'c4-hd6', name: 'Tea (Single Tea Bag)', price: 60  },
      ]},
      { cat: 'Juices', items: [
        { id: 'c4-jc1', name: 'Lassi',       price: 150 },
        { id: 'c4-jc2', name: 'Mango Juice', price: 210 },
        { id: 'c4-jc3', name: 'Peach Juice', price: 210 },
      ]},
      { cat: 'Pasta', items: [
        { id: 'c4-pas1', name: 'Crunchy Pasta', price: 450 },
      ]},
      { cat: 'Pizza', items: [
        { id: 'c4-pz1',  name: 'Bar B Q Pizza Small',            price: 450  },
        { id: 'c4-pz2',  name: 'Bar B Q Pizza Medium',           price: 900  },
        { id: 'c4-pz3',  name: 'Bar B Q Pizza Large',            price: 1250 },
        { id: 'c4-pz4',  name: 'Calzone Pizza',                  price: 500  },
        { id: 'c4-pz5',  name: 'Chapli Kabab Pizza Small',       price: 450  },
        { id: 'c4-pz6',  name: 'Chapli Kabab Pizza Medium',      price: 900  },
        { id: 'c4-pz7',  name: 'Chapli Kabab Pizza Large',       price: 1300 },
        { id: 'c4-pz8',  name: 'Cheese Pizza Small',             price: 450  },
        { id: 'c4-pz9',  name: 'Cheese Pizza Medium',            price: 900  },
        { id: 'c4-pz10', name: 'Cheese Pizza Large',             price: 1250 },
        { id: 'c4-pz11', name: 'Chicken Cheese Stuffed Pizza Medium', price: 1100 },
        { id: 'c4-pz12', name: 'Chicken Cheese Stuffed Pizza Large',  price: 1500 },
        { id: 'c4-pz13', name: 'Chicken Fajita Pizza Small',     price: 450  },
        { id: 'c4-pz14', name: 'Chicken Fajita Pizza Medium',    price: 900  },
        { id: 'c4-pz15', name: 'Chicken Fajita Pizza Large',     price: 1250 },
        { id: 'c4-pz16', name: 'Chicken Tikka Pizza Small',      price: 450  },
        { id: 'c4-pz17', name: 'Chicken Tikka Pizza Medium',     price: 900  },
        { id: 'c4-pz18', name: 'Chicken Tikka Pizza Large',      price: 1300 },
        { id: 'c4-pz19', name: 'Crown Crust Pizza Small',        price: 450  },
        { id: 'c4-pz20', name: 'Crown Crust Pizza Medium',       price: 900  },
        { id: 'c4-pz21', name: 'Crown Crust Pizza Large',        price: 1300 },
        { id: 'c4-pz22', name: 'E1 Special Pizza Small',         price: 500  },
        { id: 'c4-pz23', name: 'E1 Special Pizza Medium',        price: 1000 },
        { id: 'c4-pz24', name: 'E1 Special Pizza Large',         price: 1400 },
        { id: 'c4-pz25', name: 'Extra Topping of Cheese Small',  price: 140  },
        { id: 'c4-pz26', name: 'Extra Topping of Cheese Medium', price: 200  },
        { id: 'c4-pz27', name: 'Extra Topping of Cheese Large',  price: 250  },
        { id: 'c4-pz28', name: 'Grill Pizza Small',              price: 450  },
        { id: 'c4-pz29', name: 'Grill Pizza Medium',             price: 900  },
        { id: 'c4-pz30', name: 'Grill Pizza Large',              price: 1250 },
        { id: 'c4-pz31', name: 'Malai Boti Pizza Small',         price: 550  },
        { id: 'c4-pz32', name: 'Malai Boti Pizza Medium',        price: 1000 },
        { id: 'c4-pz33', name: 'Malai Boti Pizza Large',         price: 1400 },
        { id: 'c4-pz34', name: 'Pepperoni Pizza Small',          price: 450  },
        { id: 'c4-pz35', name: 'Pepperoni Pizza Medium',         price: 900  },
        { id: 'c4-pz36', name: 'Pepperoni Pizza Large',          price: 1250 },
        { id: 'c4-pz37', name: 'Smoke Pizza Small',              price: 450  },
        { id: 'c4-pz38', name: 'Smoke Pizza Medium',             price: 900  },
        { id: 'c4-pz39', name: 'Smoke Pizza Large',              price: 1250 },
        { id: 'c4-pz40', name: 'Supreme Pizza Small',            price: 470  },
        { id: 'c4-pz41', name: 'Supreme Pizza Medium',           price: 920  },
        { id: 'c4-pz42', name: 'Supreme Pizza Large',            price: 1250 },
      ]},
      { cat: 'Rolls', items: [
        { id: 'c4-rol1',  name: 'BBQ Roll Paratha',                  price: 280 },
        { id: 'c4-rol2',  name: 'Chicken Cheese Roll Paratha',       price: 310 },
        { id: 'c4-rol3',  name: 'Chicken Mayo Garlic Paratha Roll',  price: 280 },
        { id: 'c4-rol4',  name: 'Chicken Roll Paratha',              price: 270 },
        { id: 'c4-rol5',  name: 'Chicken Tikka Roll',                price: 280 },
        { id: 'c4-rol6',  name: 'Dhamaka Roll',                      price: 530 },
        { id: 'c4-rol7',  name: 'Malai Boti Jumbo Roll',             price: 600 },
        { id: 'c4-rol8',  name: 'Malai Boti Roll',                   price: 380 },
        { id: 'c4-rol9',  name: 'Seekh Kabab Jumbo Roll',            price: 500 },
        { id: 'c4-rol10', name: 'Seekh Kabab Roll',                  price: 300 },
        { id: 'c4-rol11', name: 'Shapata Roll',                      price: 550 },
        { id: 'c4-rol12', name: 'Tikka Jumbo Roll',                  price: 400 },
        { id: 'c4-rol13', name: 'Tortilla Wrap Roll',                price: 450 },
        { id: 'c4-rol14', name: 'Zinger Roll Paratha',               price: 340 },
        { id: 'c4-rol15', name: 'Zinger Roll Paratha with Cheese',   price: 390 },
      ]},
      { cat: 'Sandwiches', items: [
        { id: 'c4-snd1', name: 'Chicken Tikka Sandwich', price: 250 },
        { id: 'c4-snd2', name: 'Club Sandwich',          price: 350 },
      ]},
      { cat: 'Shakes', items: [
        { id: 'c4-sh1',  name: 'Apple Banana Shake', price: 210 },
        { id: 'c4-sh2',  name: 'Apple Shake',        price: 210 },
        { id: 'c4-sh3',  name: 'Banana Oreo Shake',  price: 220 },
        { id: 'c4-sh4',  name: 'Banana Shake',       price: 210 },
        { id: 'c4-sh5',  name: 'Chocolate Shake',    price: 220 },
        { id: 'c4-sh6',  name: 'Cold Coffee Shake',  price: 220 },
        { id: 'c4-sh7',  name: 'Dates Shake',        price: 230 },
        { id: 'c4-sh8',  name: 'Mango Shake',        price: 210 },
        { id: 'c4-sh9',  name: 'Milo Shake',         price: 220 },
        { id: 'c4-sh10', name: 'Oreo Shake',         price: 210 },
        { id: 'c4-sh11', name: 'Strawberry Shake',   price: 210 },
      ]},
      { cat: 'Shawarma', items: [
        { id: 'c4-sha1', name: 'Chicken Cheese Shawarma', price: 290 },
        { id: 'c4-sha2', name: 'Chicken Shawarma',        price: 250 },
      ]},
    ]
  }
];

function getCafe(id) { return CAFES.find(c => c.id === id) || null; }

function getCafeRating(cafeId) {
  const reviews = DB.where('reviews', 'cafeId', cafeId);
  if (!reviews.length) {
    const c = getCafe(cafeId);
    return { avg: c ? c.baseRating : 0, count: c ? c.baseReviews : 0 };
  }
  const avg = (reviews.reduce((s, r) => s + r.rating, 0) / reviews.length).toFixed(1);
  return { avg, count: reviews.length };
}

function renderStars(rating, size = 14) {
  const full = Math.floor(rating);
  const half = (rating % 1) >= 0.5;
  const empty = 5 - full - (half ? 1 : 0);
  const s = `width:${size}px;height:${size}px;flex-shrink:0;`;
  const starPath = 'M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z';
  let h = '';
  for (let i = 0; i < full; i++)  h += `<svg style="${s}fill:#f59e0b;" viewBox="0 0 24 24"><path d="${starPath}"/></svg>`;
  if (half)                        h += `<svg style="${s}fill:none;stroke:#f59e0b;stroke-width:1.5" viewBox="0 0 24 24"><path d="${starPath}"/></svg>`;
  for (let i = 0; i < empty; i++) h += `<svg style="${s}fill:none;stroke:rgba(245,158,11,0.3);stroke-width:1.5" viewBox="0 0 24 24"><path d="${starPath}"/></svg>`;
  return h;
}

function timeAgo(iso) {
  const diff = Date.now() - new Date(iso).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  if (d < 7) return `${d}d ago`;
  return new Date(iso).toLocaleDateString();
}

window.CAFES = CAFES;
window.getCafe = getCafe;
window.getCafeRating = getCafeRating;
window.renderStars = renderStars;
window.timeAgo = timeAgo;
